<a href="https://colab.research.google.com/github/subhan0rizwan/getting-hands-dirty-pytorch/blob/main/getting_hands_dirty_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
##LIST

my_list = [[1,2,3,5,7,8] , [2,0,5,3,77,12]]
my_list

[[1, 2, 3, 5, 7, 8], [2, 0, 5, 3, 77, 12]]

In [3]:
np1 = np.random.rand(3, 4)
np1

array([[0.32470555, 0.28661176, 0.38141494, 0.27818878],
       [0.35995493, 0.45165315, 0.2609274 , 0.8393364 ],
       [0.41403519, 0.79342823, 0.72064417, 0.73366509]])

In [4]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.7079,  0.0352,  1.2041, -0.0364],
        [ 0.1968,  0.5321,  0.4438,  0.0742],
        [ 0.4174,  0.1471, -0.3572,  0.1180]])

In [5]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 1.2981, -1.1235,  1.0406, -0.5641],
         [-0.7832, -3.0517,  1.1593, -0.6979],
         [ 0.7260,  0.2903, -0.1281, -0.8482]],

        [[ 0.3428,  0.4574, -0.8531, -0.5412],
         [-1.3952, -0.7967, -0.0759, -0.8548],
         [ 0.0950, -2.0495,  0.7827,  1.2929]]])

In [6]:
tensor_first = torch.tensor(np1)
tensor_first

tensor([[0.3247, 0.2866, 0.3814, 0.2782],
        [0.3600, 0.4517, 0.2609, 0.8393],
        [0.4140, 0.7934, 0.7206, 0.7337]], dtype=torch.float64)

In [7]:
##tensor operations

In [8]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#reshape & view
my_torch = my_torch.reshape(2,5 )
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_torch_2 = torch.arange(12)
my_torch_2 = my_torch_2.reshape(-1, 6)
my_torch_2

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [11]:
my_torch_3 = torch.arange(12)
my_torch_4 = my_torch_3.view(4,3)
my_torch_4

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [12]:
## need to search reshape & view cuz they are pretty similar

In [13]:
my_torch_5 = torch.arange(12)
my_torch_5[1] = 222
my_torch_6 = my_torch_5.reshape(2,6)
my_torch_6

tensor([[  0, 222,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11]])

In [14]:
#Slices

In [15]:
my_torch_7 = torch.arange(12)

In [16]:
#grab a specific item
my_torch_7[7]

tensor(7)

In [17]:
my_torch_8 = my_torch_7.reshape(6,2)
my_torch_8

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [18]:
#return any row
my_torch_8[:,1]

tensor([ 1,  3,  5,  7,  9, 11])

In [19]:
#return any column
my_torch_8[:,1:]

tensor([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]])

In [20]:
## math operations

In [21]:
#adding

tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,4,9,6])


tensor_a + tensor_b

tensor([ 6,  6, 12, 10])

In [22]:
#adding 2

torch.add (tensor_a, tensor_b)

tensor([ 6,  6, 12, 10])

In [23]:
#subtract

tensor_a - tensor_b

tensor([-4, -2, -6, -2])

In [27]:
#subtract 2

torch.sub(tensor_a, tensor_b)

tensor([-4, -2, -6, -2])

In [29]:
#multiply
tensor_a * tensor_b

tensor([ 5,  8, 27, 24])

In [31]:
#multiply 2

torch.mul(tensor_a, tensor_b)

tensor([ 5,  8, 27, 24])

In [32]:
#divide

tensor_a / tensor_b

tensor([0.2000, 0.5000, 0.3333, 0.6667])

In [33]:
#divide 2

torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.5000, 0.3333, 0.6667])

In [34]:
#remainders

tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [35]:
#remainders 2

torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

In [36]:
#power & exponent

torch.pow(tensor_a, tensor_b)

tensor([    1,    16, 19683,  4096])

In [37]:
#reassignment_ # use underscore after every or any torch.operatior

tensor_a.add_(tensor_b)

#making tensor_a = tensor_a + tensor_b

tensor([ 6,  6, 12, 10])

In [44]:
#a simple neural network model

In [53]:
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
iris = load_iris()

In [50]:
from math import inf
class Model(nn.Module):
  def __init__(self, in_features = 4, h1 = 8, h2 = 9, out_features = 3):
    super().__init__()
    self.fc1 = nn.Linear(in_features, h1)
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, out_features)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)

    return x

In [51]:
torch.manual_seed(41)
model = Model()

In [55]:
 url = "https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"
 my_df = pd.read_csv(url)
my_df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [56]:
my_df["variety"] = my_df["variety"].replace('Setosa', 0.0)

my_df["variety"] = my_df["variety"].replace('Versicolor', 1.0)

my_df["variety"] = my_df["variety"].replace('Virginica', 2.0)

/tmp/ipython-input-2615769293.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  my_df["variety"] = my_df["variety"].replace('Virginica', 2.0)


In [57]:
my_df

sepal.length  sepal.width  petal.length  petal.width  variety
0             5.1          3.5           1.4          0.2      0.0
1             4.9          3.0           1.4          0.2      0.0
2             4.7          3.2           1.3          0.2      0.0
3             4.6          3.1           1.5          0.2      0.0
4             5.0          3.6           1.4          0.2      0.0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3      2.0
146           6.3          2.5           5.0          1.9      2.0
147           6.5          3.0           5.2          2.0      2.0
148           6.2          3.4           5.4          2.3      2.0
149           5.9          3.0           5.1          1.8      2.0

[150 rows x 5 columns]

In [61]:
X = my_df.drop('variety', axis = 1)
y = my_df['variety']

In [62]:
X = X.values
y = y.values



In [64]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 41)

In [65]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

In [66]:
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)
