<a href="https://colab.research.google.com/github/subhan0rizwan/getting-hands-dirty-pytorch/blob/main/getting_hands_dirty_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [4]:
##LIST

my_list = [[1,2,3,5,7,8] , [2,0,5,3,77,12]]
my_list

[[1, 2, 3, 5, 7, 8], [2, 0, 5, 3, 77, 12]]

In [5]:
np1 = np.random.rand(3, 4)
np1

array([[0.54581997, 0.92303717, 0.44467215, 0.53123108],
       [0.66967346, 0.13867948, 0.47733205, 0.4469675 ],
       [0.5660666 , 0.80258898, 0.84085333, 0.03136757]])

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.6939, -0.1343, -1.5446,  0.0076],
        [ 0.0072, -0.6542, -0.7134, -0.7689],
        [-0.3387, -0.1175,  0.3280, -0.6791]])

In [10]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[-0.6669, -0.3777, -1.1104, -0.3330],
         [-0.0253,  0.5359,  1.3971, -0.0136],
         [ 1.7254, -1.2327, -0.5700, -0.3841]],

        [[ 0.1551, -2.0657,  0.1984,  1.5811],
         [-1.6529,  0.0841,  1.0243,  0.2456],
         [-0.5998,  1.9825, -2.2419,  2.5320]]])

In [14]:
tensor_first = torch.tensor(np1)
tensor_first

tensor([[0.5458, 0.9230, 0.4447, 0.5312],
        [0.6697, 0.1387, 0.4773, 0.4470],
        [0.5661, 0.8026, 0.8409, 0.0314]], dtype=torch.float64)

In [ ]:
##tensor operations

In [17]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#reshape & view
my_torch = my_torch.reshape(2,5 )
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
my_torch_2 = torch.arange(12)
my_torch_2 = my_torch_2.reshape(-1, 6)
my_torch_2

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [37]:
my_torch_3 = torch.arange(12)
my_torch_4 = my_torch_3.view(4,3)
my_torch_4

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [38]:
## need to search reshape & view cuz they are pretty similar

In [42]:
my_torch_5 = torch.arange(12)
my_torch_5[1] = 222
my_torch_6 = my_torch_5.reshape(2,6)
my_torch_6

tensor([[  0, 222,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11]])

In [43]:
#Slices

In [44]:
my_torch_7 = torch.arange(12)

In [46]:
#grab a specific item
my_torch_7[7]

tensor(7)

In [49]:
my_torch_8 = my_torch_7.reshape(6,2)

In [51]:
#return any row
my_torch_8[:,1]

tensor([ 1,  3,  5,  7,  9, 11])

In [52]:
#return any column
my_torch_8[:,1:]

tensor([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]])