<a href="https://colab.research.google.com/github/subhan0rizwan/getting-hands-dirty-pytorch/blob/main/getting_hands_dirty_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
##LIST

my_list = [[1,2,3,5,7,8] , [2,0,5,3,77,12]]
my_list

[[1, 2, 3, 5, 7, 8], [2, 0, 5, 3, 77, 12]]

In [3]:
np1 = np.random.rand(3, 4)
np1

array([[0.32470555, 0.28661176, 0.38141494, 0.27818878],
       [0.35995493, 0.45165315, 0.2609274 , 0.8393364 ],
       [0.41403519, 0.79342823, 0.72064417, 0.73366509]])

In [4]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.7079,  0.0352,  1.2041, -0.0364],
        [ 0.1968,  0.5321,  0.4438,  0.0742],
        [ 0.4174,  0.1471, -0.3572,  0.1180]])

In [5]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 1.2981, -1.1235,  1.0406, -0.5641],
         [-0.7832, -3.0517,  1.1593, -0.6979],
         [ 0.7260,  0.2903, -0.1281, -0.8482]],

        [[ 0.3428,  0.4574, -0.8531, -0.5412],
         [-1.3952, -0.7967, -0.0759, -0.8548],
         [ 0.0950, -2.0495,  0.7827,  1.2929]]])

In [6]:
tensor_first = torch.tensor(np1)
tensor_first

tensor([[0.3247, 0.2866, 0.3814, 0.2782],
        [0.3600, 0.4517, 0.2609, 0.8393],
        [0.4140, 0.7934, 0.7206, 0.7337]], dtype=torch.float64)

In [7]:
##tensor operations

In [8]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#reshape & view
my_torch = my_torch.reshape(2,5 )
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_torch_2 = torch.arange(12)
my_torch_2 = my_torch_2.reshape(-1, 6)
my_torch_2

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [11]:
my_torch_3 = torch.arange(12)
my_torch_4 = my_torch_3.view(4,3)
my_torch_4

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [12]:
## need to search reshape & view cuz they are pretty similar

In [13]:
my_torch_5 = torch.arange(12)
my_torch_5[1] = 222
my_torch_6 = my_torch_5.reshape(2,6)
my_torch_6

tensor([[  0, 222,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11]])

In [14]:
#Slices

In [15]:
my_torch_7 = torch.arange(12)

In [16]:
#grab a specific item
my_torch_7[7]

tensor(7)

In [17]:
my_torch_8 = my_torch_7.reshape(6,2)
my_torch_8

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [18]:
#return any row
my_torch_8[:,1]

tensor([ 1,  3,  5,  7,  9, 11])

In [19]:
#return any column
my_torch_8[:,1:]

tensor([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]])

In [20]:
## math operations

In [21]:
#adding

tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,4,9,6])


tensor_a + tensor_b

tensor([ 6,  6, 12, 10])

In [22]:
#adding 2

torch.add (tensor_a, tensor_b)

tensor([ 6,  6, 12, 10])

In [23]:
#subtract

tensor_a - tensor_b

tensor([-4, -2, -6, -2])

In [27]:
#subtract 2

torch.sub(tensor_a, tensor_b)

tensor([-4, -2, -6, -2])

In [29]:
#multiply
tensor_a * tensor_b

tensor([ 5,  8, 27, 24])

In [31]:
#multiply 2

torch.mul(tensor_a, tensor_b)

tensor([ 5,  8, 27, 24])

In [32]:
#divide

tensor_a / tensor_b

tensor([0.2000, 0.5000, 0.3333, 0.6667])

In [33]:
#divide 2

torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.5000, 0.3333, 0.6667])

In [34]:
#remainders

tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [35]:
#remainders 2

torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

In [36]:
#power & exponent

torch.pow(tensor_a, tensor_b)

tensor([    1,    16, 19683,  4096])

In [37]:
#reassignment_ # use underscore after every or any torch.operatior

tensor_a.add_(tensor_b)

#making tensor_a = tensor_a + tensor_b

tensor([ 6,  6, 12, 10])